"""Initial migration

Revision ID: 925489eadde5
Revises: 
Create Date: 2025-12-04 16:44:23.869183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925489eadde5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('bidding_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bidding_products_name'), 'bidding_products', ['name'], unique=False)
    op.create_table('bidding_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('upset_price', sa.Float(), nullable=False),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('gamma', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['bidding_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bidding_sessions_end_time'), 'bidding_sessions', ['end_time'], unique=False)
    op.create_index(op.f('ix_bidding_sessions_start_time'), 'bidding_sessions', ['start_time'], unique=False)
    op.create_table('bidding_session_bids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bid_price', sa.Float(), nullable=False),
    sa.Column('bid_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['bidding_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bidding_session_bids_session_id'), 'bidding_session_bids', ['session_id'], unique=False)
    op.create_index(op.f('ix_bidding_session_bids_user_id'), 'bidding_session_bids', ['user_id'], unique=False)
    op.create_table('bidding_session_rankings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=False),
    sa.Column('bid_price', sa.Float(), nullable=False),
    sa.Column('bid_score', sa.Float(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['bidding_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bidding_session_rankings_session_id'), 'bidding_session_rankings', ['session_id'], unique=False)
    op.create_index(op.f('ix_bidding_session_rankings_user_id'), 'bidding_session_rankings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bidding_session_rankings_user_id'), table_name='bidding_session_rankings')
    op.drop_index(op.f('ix_bidding_session_rankings_session_id'), table_name='bidding_session_rankings')
    op.drop_table('bidding_session_rankings')
    op.drop_index(op.f('ix_bidding_session_bids_user_id'), table_name='bidding_session_bids')
    op.drop_index(op.f('ix_bidding_session_bids_session_id'), table_name='bidding_session_bids')
    op.drop_table('bidding_session_bids')
    op.drop_index(op.f('ix_bidding_sessions_start_time'), table_name='bidding_sessions')
    op.drop_index(op.f('ix_bidding_sessions_end_time'), table_name='bidding_sessions')
    op.drop_table('bidding_sessions')
    op.drop_index(op.f('ix_bidding_products_name'), table_name='bidding_products')
    op.drop_table('bidding_products')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
